version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zahid
      POSTGRES_PASSWORD: zahid
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
